SET SCHEMA hybench1x_column;

CREATE TABLE customer (
custID int,
companyID int,
gender char(6),
name char(15),
age int,
phone char(11),
province char(15),
city char(15),
loan_balance real,
saving_credit int,
checking_credit int,
loan_credit int,
Isblocked int,
created_date timestamp,
last_update_timestamp timestamp,
primary key(custid)
);

CREATE TABLE company (
companyID int,
name varchar,
category varchar,
staff_size int,
loan_balance real,
phone char(11),
province char(15),
city char(15),
saving_credit int,
checking_credit int,
loan_credit int,
Isblocked int,
created_date timestamp,
last_update_timestamp timestamp,
PRIMARY KEY(companyID)
);

CREATE TABLE savingAccount (
 accountID int,
 userID int,
 balance real,
 Isblocked int,
 timestamp timestamp,
 fresh_ts timestamp default current_timestamp,
 PRIMARY KEY(accountID)
);


CREATE TABLE checkingAccount (
accountID int,
userID int,
balance real,
Isblocked int,
timestamp timestamp,
PRIMARY KEY(accountID)
);

CREATE TABLE transfer (
  id int GENERATED BY DEFAULT AS IDENTITY,
  sourceID int,
  targetID int,
  amount real,
  type char(10),
  timestamp timestamp,
  fresh_ts timestamp default current_timestamp,
  PRIMARY KEY(id)
);

CREATE TABLE checking (
  id int GENERATED BY DEFAULT AS IDENTITY,
  sourceID int,
  targetID int,
  amount real,
  type char(10),
  timestamp timestamp,
  PRIMARY KEY(id)
);

CREATE TABLE loanapps (
  id int GENERATED BY DEFAULT AS IDENTITY,
  applicantID int,
  amount real,
  duration int,
  status char(12),
  timestamp timestamp,
  PRIMARY KEY(id)
);

CREATE TABLE loantrans (
  id int GENERATED BY DEFAULT AS IDENTITY,
  applicantID int,
  appID int,
  amount real,
  status char(12),
  timestamp timestamp,
  duration int,
  contract_timestamp timestamp,
  delinquency int,
  PRIMARY KEY(id)
);
